import { SideBar } from '@/components/Sidebar'
import { PageContainerLayout } from '@/components/PageContainerLayout'
import Head from 'next/head'

export default function Home() {

  return (
    <>
      <Head>
        <title>Smartseg</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainerLayout
        sidebar={<SideBar current="/" />}
        content={
          <div>
            
          </div>
        }
      />
    </>
  )
}
